### PR TITLE
Package debugging

### LINKED ISSUE #104: Package Debugging
*(Follow-up on https://github.com/ManuelHentschel/VSCode-R-Debugger/issues/56, @pat-s)*

In [VSCode-R-Debugger/packageDebugging](https://github.com/ManuelHentschel/VSCode-R-Debugger/tree/packageDebugging) and [vscDebugger/packageDebugging](https://github.com/ManuelHentschel/vscDebugger/tree/packageDebugging), I've started working on making the workflow for debugging packages more "dynamic".

I've added the debug config entry `loadPackages`, which indicates paths (!) to packages that are loaded with `pkgload::load_all` before launching the debugger. To load the package from the working directory, this entry can be set to `["."]`. To set breakpoints in these packages it is currently necessary to set `"setBreakpointsInPackages": true`. An example launch config that can be used to debug the package from the current wd could be:
``` jsonc
        {
            "type": "R-Debugger",
            "request": "launch",
            "name": "Launch Workspace",
            "debugMode": "workspace",
            "workingDirectory": "${workspaceFolder}",
            "loadPackages": ["."],
            "setBreakpointsInPackages": true,
            "includePackageScopes": true,
            "allowGlobalDebugging": true
        }
```

Some considerations/questions I have about how to continue from here:
* Manually calling `load_all` resets all breakpoints set in the loaded package. This could be solved by replacing the function with a wrapper around the original function, that also sets the breakpoints. In that case it might not even be necessary to specify "loadPackages", since the breakpoints will be set anyways.
* Currently, "setBreakpointsInPackages" is disabled by default and limited to exported functions, because I experienced some performance hits when looking for multiple breakpoints in the exported+private functions from every package. An option here might be to skip R's standard packages (base, utils, methods, ...), but still look in all custom packages.
* Only allowing the user to specify the package path might be a bit inflexible, if users want to pass custom arguments to `load_all`, or maybe even use an entirely different function to load their package. In that case it might make sense to allow the user to specify "pre-launch-commands" instead, that are executed before setting breakpoints and overwriting print/cat/message.

Any thoughts on the points above or debugging-scenarios I am missing? :)

### PR DESCRIPTION
**Pull request by ManuelHentschel**
Fix #104 

This PR and https://github.com/ManuelHentschel/vscDebugger/pull/134 add functionality to debug packages more dynamically:
* Add function `.vsc.load_all`, which is attached as `load_all` by default. This function internally calls `pkgload::load_all` and then refreshes breakpoints in the loaded package and attaches an environment containing the modified versions of `print`, `cat` etc.
* Add launch config entry `loadPackages`: The paths specified here are passed to `.vsc.load_all` on launch. Can be set to e.g. `["."]` to debug the package in the current wd, or to the path of a package located elsewhere
* Add launch config entry `loadSilently`: suppresses message during `.vsc.load_all`

### CODE REVIEW

**Comment by ManuelHentschel** [comment]
@pat-s do these changes work for you?:)

**Comment by pat-s** [comment]
Thanks for working on this!

I've played around a bit with the latest versions of the package and the extensions but might be doing something wrong.

Could you give me a configuration which I should use in `launch.json`?

Also have you thought about shipping an explicit "DebugPackage" (or similar) mode?

**Comment by ManuelHentschel** [comment]
Sure, in fact the default `launch.json` should work. The following steps should work to debug a package (at least they do on my machine...):
* Open vscode in a the root folder of a package
* Open any `.R` file
* Delete `.vscode/launch.json` if there is one
* Create the default `launch.json` by pressing `Ctrl+Shift+D` then clicking `create a launch.json file`
* Make sure the selected launch config is `Launch Workspace`
* Press F5 to launch the debug session
* Enter `load_all()` in the debug console (the one opened with `Ctrl+Shift+Y`)
* Set a breakpoint in one of the functions from your package
* Call said function from your package in the debug console

 Expected behavior: Your package is loaded (as if using `pkgload::load_all()`) and the execution of the package function stops when hitting your breakpoint.

**Comment by pat-s** [comment]
Thanks for the defailed instructions! Deleting previous launch configs is certainly an important point - I see how this could cause troubles for users if new features are added/old ones removed and there is manual action required to update the local config after updating the extension.

I still cannot get it to work following your instructions - here is what I do and what happens:

1. Launch debug session
1. Call `load_all()`
1. Set a breakpoint or insert a `browser()` 
1. Call the function with the breakspoints in the debug console

What is happening: After executing the function it does not stop at either the `browser()` nor the set breakpoint.
I also tried installing the package beforehand with `keep_source = TRUE` explicitly and calling `pkgload::load_call()` again when in the debug console.

Question: Would it be possible to call the custom `load_all()` automatically in the background after the debug console has started?

I am using the following `launch.json` config

```json
            "type": "R-Debugger",
            "request": "launch",
            "name": "Launch Workspace",
            "debugMode": "workspace",
            "workingDirectory": "${workspaceFolder}",
            "allowGlobalDebugging": true
```

**Comment by ManuelHentschel** [comment]
Just to be sure, be careful to only use `load_all()`, not `pkgload::load_all`. Any changes I made do not affect the original `pkgload::load_all`.

---

> ...
> * Set a breakpoint or insert a `browser()`
> * Call the function with the breakspoints in the debug console

If you modify the code (e.g. by inserting `browser()`) you need to call `load_all()` again to load the new version of the code.The `browser()` statements should work independently of whether you used the modified `load_all` or the original `pkgload::load_all` (as they did before).

---


> Question: Would it be possible to call the custom `load_all()` automatically in the background after the debug console has started?

This can be achieved by adding `loadPackages` to your debug config:
``` jsonc
{
    "type": "R-Debugger",
    "request": "launch",
    "name": "Launch Workspace",
    "debugMode": "workspace",
    "workingDirectory": "${workspaceFolder}",
    "loadPackages": ["."],
    "allowGlobalDebugging": true
}
```

---

> Also have you thought about shipping an explicit "DebugPackage" (or similar) mode?

This would be possible, but I am not sure what such a configuration would look like. E.g. depending on the user's preferences, it can make sense to debug a package using either of the three `debugMode`s (`workspace`, `file`, `function`). 

---

**Comment by pat-s** [comment]
🤦 to myself: I still had R term set to `radian`.

Happy to report that it works! And its really great 🎉 

With `"loadPackages": ["."]` one can start the debugger, set multiple breakpoints and then just call the function which should be debugged. Awesome!

I'd vote for this config to be the default and bundle it in a name called "Debug R package" or similar to make it fully clear for the user.

I also tried it with a quite large package which has a higher loading footprint and a longer stacktrace - the debugger ran instant.

PS: If you merge this at some point and want to promote it, I'd highly recommend sharing this great project with the R community also on [RWeekly](https://rweekly.org/).

**Comment by ManuelHentschel** [comment]
> I'd vote for this config to be the default and bundle it in a name called "Debug R package" or similar, simply to make it fully clear for the user which mode to use in a package scenario.

I added a "Debug R Package" config as you suggested and made it the default if the debugger is launched without launch.json from a workspace that contains a file named DESCRIPTION. This might surprise users that are not used to working on packages and will cause an error if `pkgload` is not installed. So we might need to add an option in vscode that toggles this behaviour.

**Comment by ManuelHentschel** [comment]
If there are no more issues with this branch I'll merge it soon and also release a new version to the vscode marketplace

**Comment by renkun-ken** [comment]
Definitely like using this way to debug a package!

**Pull request merged**
